import { LayerState, Shape } from './model/layerTypes';

export const initialState: LayerState[] = [
  {
    shape: Shape.LINE,
    name: 'Inter City Roads',
    layer: 'transport_lines',
    // text: 'name',
    type: ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'],
    style: { stroke: { color: 'rgb(255, 255, 255, 0.6)', width: 3 } },
    show: true,
  },
  {
    shape: Shape.LINE,
    name: 'City Roads',
    layer: 'transport_lines',
    type: ['residential'],
    style: { stroke: { color: 'rgb(204, 204, 0, 0.6)', width: 3 } },
    show: true,
  },
  {
    shape: Shape.LINE,
    name: 'Footway Roads',
    layer: 'transport_lines',
    type: ['footway', 'pedestrian'],
    style: { stroke: { color: 'rgb(204, 255, 153, 0.6)', width: 3 } },
    show: true,
  },
  {
    shape: Shape.POLYGON,
    name: 'Parks',
    layer: 'landuse_areas',
    text: 'name',
    type: ['park'],
    style: {
      fill: { color: 'rgb(204, 255, 153, 0.4)' },
      stroke: { color: 'rgb(34, 139, 34)', width: 2 },
    },
    show: false,
  },
  {
    shape: Shape.POINT,
    name: 'Benches',
    layer: 'amenity_points',
    type: ['bench'],
    style: { useSprite: true, icon: 'picnic-site-11' },
    show: false,
  },
  {
    shape: Shape.POINT,
    name: 'Restaurants',
    layer: 'amenity_points',
    type: ['fast_food', 'restaurant', 'cafe'],
    style: { useSprite: true, icon: 'restaurant-11' },
    show: false,
  },
  {
    shape: Shape.POINT,
    name: 'Bus Stops',
    layer: 'transport_points',
    type: ['bus_stop'],
    style: { useSprite: true, icon: 'bus-11' },
    show: false,
  },
  {
    shape: Shape.POINT,
    name: 'Gas Stations',
    layer: 'amenity_points',
    type: ['fuel'],
    style: { useSprite: true, icon: 'fuel-15' },
    show: false,
  },
  {
    shape: Shape.POINT,
    name: 'Traffic Lights',
    layer: 'transport_points',
    type: ['traffic_signals'],
    style: {
      useSprite: false,
      circle: { radius: 5, fill: { color: 'chocolate' } },
    },
    show: false,
  },
];
